# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtSql import *
import sys #el modulo provee acceso a funciones y objetos mantenidos por del interprete
import sqlite3 #activamos la base de datos de sqlite
from sqlite3 import Error #aqui importamos error para saber si las lineas de codigo estan mal y te tiren el error


class Ui_Cliente(object):
    
    def mostrar(self):
        try: #se ubica todo el codigo que puede llegar a levantar una excepcion
            connection = sqlite3.connect('TiendaDreamPotion.db') #abres la base de datos para que muestre los datos
            query = "SELECT * FROM Cliente " #aqui vamos a mostrar todos los registros que hemos hecho
            result = connection.execute(query)
            self.tableWidget.setRowCount(0) #va a contar columnas o filas para mostrar datos
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
        except Error as e: #la excepcion le decimos error y que le nombre con la letra e en vez de poner error todo el nombre
            print (e) #imprimi el error
        except:
            print(f"Se produjo el siguiente error: {sys.exc_info()[0]}") #te va a tirar el tipo de error si es class error o name error etc.
        connection.close() #cierra la base de datos
        
    def Insertar(self):
        try: #aqui tenemos un try para que cheque el codigo y si algo esta mal pase a la excepcion
            conn = sqlite3.connect('TiendaDreamPotion.db')
            c = conn.cursor()
            
            id_Cliente = self.Id_cliente.toPlainText() #ponemos aqui cuadros texto donde pusimos en qt designer Text edit donde tu puedas escribir y puedas insertar datos
            nombre = self.Nombre.toPlainText()
            telefono = self.Telefono.toPlainText()
            correo = self.Correo.toPlainText()
            direccion = self.Direccion.toPlainText()
            
            c.execute("INSERT INTO Cliente(Id_Cliente, Nombre, Telefono, Correo, Direccion) VALUES (?,?,?,?,?)",
                      (id_Cliente, nombre, telefono, correo, direccion)) #como sql estamos insertando datos y lo que esta en parentesis es lo que anotamos en los cuadros por eso los llamamos para que inserte los datos en sqlite
            print("Registro De Cliente Insertardo") #ponemos un print para saber si esta registrando datos
        except Error as e: #aqui tenemos una excepcion por si el codigo esta mal o apunta un mal dato pues se va rapidamente a la excepcion
            print (e) #imprime el error
        except:
            print(f"Se produjo el siguiente error: {sys.exc_info()[0]}") #aqui nos dice el tipo de error que es
        conn.commit()
        
    def eliminar(self):
        try:
            conn = sqlite3.connect('TiendaDreamPotion.db')
            c = conn.cursor()
            id_Cliente = int(self.Id_cliente.toPlainText())
            
            c.execute("DELETE FROM Cliente WHERE Id_Cliente="+str(id_Cliente)) #borramos todo el registro del cliente pero poniendo una una clausula where para que se cumpla condicion para que sepas que tipo de cliente vas a borrar con el id
            print("Registro De Cliente Eliminado") #para que sepamos si borramos el registro o no 
        except Error as e:
            print (e)
        except:
            print(f"Se produjo el siguiente error: {sys.exc_info()[0]}")
        conn.commit()
        
    def Modificar(self):
        try:
            conn = sqlite3.connect('TiendaDreamPotion.db')
            c = conn.cursor()
            
            id_Cliente = self.Id_cliente.toPlainText() #los cuadros de texto la funcion para que cuando la llames se inserten esos datos en el cuadro y se pongan en la base de datos
            nombre = self.Nombre.toPlainText()
            telefono = self.Telefono.toPlainText()
            correo = self.Correo.toPlainText()
            direccion = self.Direccion.toPlainText()
            
            c.execute("""UPDATE Cliente SET Id_Cliente = ?, Nombre = ?, Telefono = ?, Correo = ?, Direccion = ? WHERE Id_Cliente = ?""",
                      (id_Cliente, nombre, telefono, correo, direccion, str(id_Cliente))) #para modificar el cliente todos los campos del cliente pero con la clausula where para que tipo de cliente quieres modificar y lo que esta entre paretensis para que sepa que cuadros de qt designer va a modificar
            print("Registro De Cliente Modificado")
            
        except Error as e:
            print (e)
        except:
            print(f"Se produjo el siguiente error: {sys.exc_info()[0]}")
        conn.commit()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Cliente")
        MainWindow.resize(641, 493)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 91, 16))
        self.label_2.setObjectName("label_2")
        self.Id_cliente = QtWidgets.QTextEdit(self.centralwidget)
        self.Id_cliente.setGeometry(QtCore.QRect(80, 0, 401, 21))
        self.Id_cliente.setObjectName("Id_cliente")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 91, 16))
        self.label.setObjectName("label")
        self.Nombre = QtWidgets.QTextEdit(self.centralwidget)
        self.Nombre.setGeometry(QtCore.QRect(80, 40, 401, 21))
        self.Nombre.setObjectName("Nombre")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 91, 16))
        self.label_3.setObjectName("label_3")
        self.Telefono = QtWidgets.QTextEdit(self.centralwidget)
        self.Telefono.setGeometry(QtCore.QRect(80, 80, 401, 21))
        self.Telefono.setObjectName("Telefono")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 91, 16))
        self.label_5.setObjectName("label_5")
        self.Correo = QtWidgets.QTextEdit(self.centralwidget)
        self.Correo.setGeometry(QtCore.QRect(80, 120, 401, 21))
        self.Correo.setObjectName("Correo")
        self.Direccion = QtWidgets.QTextEdit(self.centralwidget)
        self.Direccion.setGeometry(QtCore.QRect(80, 150, 401, 21))
        self.Direccion.setObjectName("Direccion")
        self.insertarTab = QtWidgets.QPushButton(self.centralwidget)
        self.insertarTab.setGeometry(QtCore.QRect(520, 0, 91, 21))
        self.insertarTab.setObjectName("insertarTab")
        
        self.insertarTab.clicked.connect(self.Insertar) #es donde el boton es donde va insertar los datos
        
        self.modificarTab = QtWidgets.QPushButton(self.centralwidget)
        self.modificarTab.setGeometry(QtCore.QRect(520, 40, 91, 21))
        self.modificarTab.setObjectName("modificarTab")
        
        self.modificarTab.clicked.connect(self.Modificar) #es el boton para modificar los datos
        
        self.mostrarTab = QtWidgets.QPushButton(self.centralwidget)
        self.mostrarTab.setGeometry(QtCore.QRect(520, 80, 91, 21))
        self.mostrarTab.setObjectName("mostrarTab")
        
        self.mostrarTab.clicked.connect(self.mostrar)# es el boton para mostrar los datos
        
        self.eliminarTab = QtWidgets.QPushButton(self.centralwidget)
        self.eliminarTab.setGeometry(QtCore.QRect(520, 120, 91, 21))
        self.eliminarTab.setObjectName("eliminarTab")
        
        self.eliminarTab.clicked.connect(self.eliminar)# es el boton para eliminar los datos
        
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 180, 641, 311))
        self.tableWidget.setRowCount(100)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.insertarTab.clicked.connect(self.Id_cliente.clear)
        self.insertarTab.clicked.connect(self.Nombre.clear)
        self.insertarTab.clicked.connect(self.Telefono.clear)
        self.insertarTab.clicked.connect(self.Correo.clear)
        self.insertarTab.clicked.connect(self.Direccion.clear)
        self.eliminarTab.clicked.connect(self.Id_cliente.clear)
        self.eliminarTab.clicked.connect(self.Nombre.clear)
        self.eliminarTab.clicked.connect(self.Telefono.clear)
        self.eliminarTab.clicked.connect(self.Correo.clear)
        self.eliminarTab.clicked.connect(self.Direccion.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Id_Cliente"))
        self.label.setText(_translate("MainWindow", "Nombre"))
        self.label_3.setText(_translate("MainWindow", "Telefono"))
        self.label_4.setText(_translate("MainWindow", "Correo"))
        self.label_5.setText(_translate("MainWindow", "Direccion"))
        self.insertarTab.setText(_translate("MainWindow", "Insertar"))
        self.modificarTab.setText(_translate("MainWindow", "Modificar"))
        self.mostrarTab.setText(_translate("MainWindow", "Mostrar"))
        self.eliminarTab.setText(_translate("MainWindow", "Eliminar"))

