# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Factura.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtSql import *
import sys
import sqlite3
from sqlite3 import Error


class Ui_Factura(object):
    def mostrar(self):
        try:
            connection = sqlite3.connect('TiendaDreamPotion.db')
            query = "SELECT * FROM Factura"
            result = connection.execute(query)
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
        except Error as e:
            print (e)
        except:
            print(f"Se produjo el siguiente error: {sys.exc_info()[0]}")
        connection.close()
        
    def Insertar(self):
        try:
            conn = sqlite3.connect('TiendaDreamPotion.db')
            c = conn.cursor()
            
            Numero_Factura = self.num_fac.toPlainText()
            id_Cliente = self.id_cliente.toPlainText()
            id_Juego = self.id_juego.toPlainText()
            fecha_factura = self.fecha.toPlainText()
            MOnto = self.monto.toPlainText()
            
            c.execute("INSERT INTO Factura(Num_Factura, Id_Cliente, Id_Juego, Fecha, Monto) VALUES (?,?,?,?,?)",
                      (Numero_Factura, id_Cliente, id_Juego, fecha_factura, MOnto))
            print("Registro De Factura Insertardo")
        except Error as e:
            print (e)
        except:
            print(f"Se produjo el siguiente error: {sys.exc_info()[0]}")
        conn.commit()
        
    def eliminar(self):
        try:
            conn = sqlite3.connect('TiendaDreamPotion.db')
            c = conn.cursor()
            Numero_Factura = int(self.num_fac.toPlainText())
            
            c.execute("DELETE FROM Factura WHERE  Num_Factura ="+str(Numero_Factura))
            print("Registro De Factura Eliminado")
        except Error as e:
            print (e)
        except:
            print(f"Se produjo el siguiente error: {sys.exc_info()[0]}")
        conn.commit()
        
    def Modificar(self):
        try:
            conn = sqlite3.connect('TiendaDreamPotion.db')
            c = conn.cursor()
            
            Numero_Factura = self.num_fac.toPlainText()
            id_Cliente = self.id_cliente.toPlainText()
            id_Juego = self.id_juego.toPlainText()
            fecha_factura = self.fecha.toPlainText()
            MOnto = self.monto.toPlainText()
            
            c.execute("""UPDATE Factura SET Num_Factura = ?, Id_Cliente = ?, Id_Juego = ?, Fecha = ?, Monto = ? WHERE Num_Factura = ?""",
                      (Numero_Factura, id_Cliente, id_Juego, fecha_factura, MOnto, str(Numero_Factura)))
            print("Registro De Factura Modificado")
            
        except Error as e:
            print (e)
        except:
            print(f"Se produjo el siguiente error: {sys.exc_info()[0]}")
        conn.commit()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Factura")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.num_fac = QtWidgets.QTextEdit(self.centralwidget)
        self.num_fac.setGeometry(QtCore.QRect(80, 10, 401, 21))
        self.num_fac.setObjectName("num_fac")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(-10, 10, 101, 61))
        self.label_6.setObjectName("label_6")
        self.id_cliente = QtWidgets.QTextEdit(self.centralwidget)
        self.id_cliente.setGeometry(QtCore.QRect(80, 50, 401, 21))
        self.id_cliente.setObjectName("id_cliente")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(-10, 10, 101, 101))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(-10, 70, 101, 101))
        self.label_8.setObjectName("label_8")
        self.id_juego = QtWidgets.QTextEdit(self.centralwidget)
        self.id_juego.setGeometry(QtCore.QRect(80, 90, 401, 21))
        self.id_juego.setObjectName("id_juego")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(-10, 110, 101, 101))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(-10, 150, 101, 101))
        self.label_10.setObjectName("label_10")
        self.fecha = QtWidgets.QTextEdit(self.centralwidget)
        self.fecha.setGeometry(QtCore.QRect(80, 130, 401, 21))
        self.fecha.setObjectName("fecha")
        self.monto = QtWidgets.QTextEdit(self.centralwidget)
        self.monto.setGeometry(QtCore.QRect(80, 170, 401, 21))
        self.monto.setObjectName("monto")
        self.insertar_f = QtWidgets.QPushButton(self.centralwidget)
        self.insertar_f.setGeometry(QtCore.QRect(520, 10, 91, 21))
        self.insertar_f.setObjectName("insertar_f")
        
        self.insertar_f.clicked.connect(self.Insertar)
        
        self.modificar_f = QtWidgets.QPushButton(self.centralwidget)
        self.modificar_f.setGeometry(QtCore.QRect(520, 50, 91, 21))
        self.modificar_f.setObjectName("modificar_f")
        
        self.modificar_f.clicked.connect(self.Modificar)
        
        self.mostrar_f = QtWidgets.QPushButton(self.centralwidget)
        self.mostrar_f.setGeometry(QtCore.QRect(520, 90, 91, 21))
        self.mostrar_f.setObjectName("mostrar_f")
        
        self.mostrar_f.clicked.connect(self.mostrar)
        
        self.eliminar_f = QtWidgets.QPushButton(self.centralwidget)
        self.eliminar_f.setGeometry(QtCore.QRect(520, 130, 91, 21))
        self.eliminar_f.setObjectName("eliminar_f")
        
        self.eliminar_f.clicked.connect(self.eliminar)
        
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 200, 641, 231))
        self.tableWidget.setRowCount(60)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.insertar_f.clicked.connect(self.num_fac.clear)
        self.insertar_f.clicked.connect(self.id_cliente.clear)
        self.insertar_f.clicked.connect(self.id_juego.clear)
        self.insertar_f.clicked.connect(self.fecha.clear)
        self.insertar_f.clicked.connect(self.monto.clear)
        self.eliminar_f.clicked.connect(self.num_fac.clear)
        self.eliminar_f.clicked.connect(self.id_cliente.clear)
        self.eliminar_f.clicked.connect(self.id_juego.clear)
        self.eliminar_f.clicked.connect(self.fecha.clear)
        self.eliminar_f.clicked.connect(self.monto.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Numero Factura</p><p align=\"center\"><br/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Id_Cliente</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Id_Juego</p><p align=\"center\"><br/></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Fecha</p><p align=\"center\"><br/></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Monto</p><p align=\"center\"><br/></p></body></html>"))
        self.insertar_f.setText(_translate("MainWindow", "Insertar"))
        self.modificar_f.setText(_translate("MainWindow", "Modificar"))
        self.mostrar_f.setText(_translate("MainWindow", "Mostrar"))
        self.eliminar_f.setText(_translate("MainWindow", "Eliminar"))
